---
prometheus-openstack-exporter:
  - 0.1.0 Initial Chart
  - 0.1.1 Change helm-toolkit dependency version to ">= 0.1.0"
  - 0.1.2 Unpin prometheus-openstack-exporter image
  - 0.1.3 Add possibility to use overrides for some charts
  - 0.1.4 Use full image ref for docker official images
  - 0.1.5 Helm 3 - Fix Job labels
  - 0.1.6 Update htk requirements
...
