---
prometheus-alertmanager:
  - 0.1.0 Initial Chart
  - 0.1.1 Change helm-toolkit dependency version to ">= 0.1.0"
  - 0.1.2 Add extensible command line flags to Alertmanager
  - 0.1.3 Add LDAP to Alertmanager
  - 0.1.4 Remove snmp_notifier subchart from alertmanager
  - 0.1.5 Add Prometheus Scrape Annotation
  - 0.1.6 Remove Alerta from openstack-helm-infra repository
  - 0.1.7 Use full image ref for docker official images
  - 0.1.8 Update htk requirements
...
