---
prometheus-kube-state-metrics:
  - 0.1.0 Initial Chart
  - 0.1.1 Change helm-toolkit dependency version to ">= 0.1.0"
  - 0.1.2 Update to make current
  - 0.1.3 Update image version from v2.0.0-alpha to v2.0.0-alpha-1
  - 0.1.4 Use full image ref for docker official images
  - 0.1.5 Fix helm3 compatability
  - 0.1.6 Update htk requirements
...
