---
branch: master
collapse_pre_releases: false
stop_at_branch_base: true
sections:
  - [ca-issuer, ca-issuer Chart]
  - [calico, calico Chart]
  - [ceph-client, ceph-client Chart]
  - [ceph-mon, ceph-mon Chart]
  - [ceph-osd, ceph-osd Chart]
  - [ceph-provisioners, ceph-provisioners Chart]
  - [daemonjob-controller, daemonjob-controller Chart]
  - [elastic-apm-server, elastic-apm-server Chart]
  - [elastic-filebeat, elastic-filebeat Chart]
  - [elastic-metricbeat, elastic-metricbeat Chart]
  - [elastic-packetbeat, elastic-packetbeat Chart]
  - [elasticsearch, elasticsearch Chart]
  - [etcd, etcd Chart]
  - [falco, falco Chart]
  - [flannel, flannel Chart]
  - [fluentbit, fluentbit Chart]
  - [fluentd, fluentd Chart]
  - [grafana, grafana Chart]
  - [helm-toolkit, helm-toolkit Chart]
  - [ingress, ingress Chart]
  - [kibana, kibana Chart]
  - [kube-dns, kube-dns Chart]
  - [kubernetes-keystone-webhook, kubernetes-keystone-webhook Chart]
  - [kubernetes-node-problem-detector, kubernetes-node-problem-detector Chart]
  - [ldap, ldap Chart]
  - [libvirt, libvirt Chart]
  - [local-storage, local-storage Chart]
  - [lockdown, lockdown Chart]
  - [mariadb, mariadb Chart]
  - [memcached, memcached Chart]
  - [metacontroller, metacontroller Chart]
  - [mongodb, mongodb Chart]
  - [nagios, nagios Chart]
  - [namespace-config, namespace-config Chart]
  - [nfs-provisioner, nfs-provisioner Chart]
  - [openvswitch, openvswitch Chart]
  - [podsecuritypolicy, podsecuritypolicy Chart]
  - [postgresql, postgresql Chart]
  - [powerdns, powerdns Chart]
  - [prometheus, prometheus Chart]
  - [prometheus-alertmanager, prometheus-alertmanager Chart]
  - [prometheus-blackbox-exporter, prometheus-blackbox-exporter Chart]
  - [prometheus-kube-state-metrics, prometheus-kube-state-metrics Chart]
  - [prometheus-node-exporter, prometheus-node-exporter Chart]
  - [prometheus-openstack-exporter, prometheus-openstack-exporter Chart]
  - [prometheus-process-exporter, prometheus-process-exporter Chart]
  - [rabbitmq, rabbitmq Chart]
  - [redis, redis Chart]
  - [registry, registry Chart]
  - [shaker, shaker Chart]
  - [features, New Features]
  - [issues, Known Issues]
  - [upgrade, Upgrade Notes]
  - [api, API Changes]
  - [security, Security Issues]
  - [fixes, Bug Fixes]
...
